food_stories/api/urls.py
from django.urls import path
from api.views import recipes_api, recipe, SubscriberCreateAPIView
from api.routers import router

urlpatterns = [
    path('recipes/', recipes_api, name='api_recipes'),
    path('recipes/<int:id>/', recipe, name='api_recipe'),
    path('subscribe/', SubscriberCreateAPIView.as_view(), name='subscribe'),
] + router.urls

food_stories/food_stories/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('jet/', include('jet.urls', 'jet')),  # Django JET URLS
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS
    path('admin/', admin.site.urls),
    path('', include('stories.urls')),
    path('api/v1.0/', include('api.urls')),
    path('api/v1.0/auth/', include('accounts.api.urls', namespace='api_account')),
    path('', include('social_django.urls', namespace="social")),
    path('auth/', include('accounts.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
] 

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

food_stories/stories/urls.py
from django.urls import path
from stories.views import HomePage, about, recipes, recipe_detail, StoryListView, StoryDetailView, ContactView, \
    CreateStoryView, StoryUpdateView, StoryDeleteView, manage, CreateRecipeView, SaveRecipeView, \
        SavedRecipeListView, export_excel_view, SubscriberCreateView

urlpatterns = [
    path('', HomePage.as_view(), name='home'),
    path('about/', about, name='about'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('recipes/', recipes, name='recipes'),
    path('stories/', StoryListView.as_view(), name='stories'),
    path('create-story/', CreateStoryView.as_view(), name='create_story'),
    path('create-recipe/', CreateRecipeView.as_view(), name='create_recipe'),
    path('delete-story/<str:slug>/', StoryDeleteView.as_view(), name='delete_story'),
    path('update-story/<str:slug>/', StoryUpdateView.as_view(), name='update_story'),
    path('stories/<str:slug>/', StoryDetailView.as_view(), name='story_detail'),
    path('recipes/<str:slug>/', recipe_detail, name='recipe_detail'),
    path('save-recipe/<int:pk>/', SaveRecipeView.as_view(), name='save_recipe'),
    path('saved-recipes/', SavedRecipeListView.as_view(), name='saved_recipes'),
    path('manage/', manage, name='manage'),
    path('export/', export_excel_view, name='export_excel_view'),
    path('subscribe/', SubscriberCreateView.as_view(), name='subscribe'),
]

food_stories/stories/models.py
import math
from django.db import models
from django.contrib.auth import get_user_model
from stories.tools.slug_generator import slugify
from datetime import datetime
from ckeditor.fields import RichTextField
from django.urls import reverse_lazy

USER_MODEL = get_user_model()


class Category(models.Model):
    """
    Bu model reseptlerin ve storilerin kategoriyalarini saxlamaq ucundu.
    Misal: Deset, Yemek
    """

    #informations
    title = models.CharField('Title', max_length=120)
    image = models.ImageField('Image', upload_to='category_images')

    # moderations
    is_published = models.BooleanField('is published', default=True)
    order = models.PositiveIntegerField('Order', default=1)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'
        ordering = ('order',)
    
    def __str__(self):
        return self.title


class Tag(models.Model):

    #information
    title = models.CharField('Title', max_length=40)

    # moderations
    is_published = models.BooleanField('is published', default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        verbose_name = 'Tag'
        verbose_name_plural = 'Tag'
    
    def __str__(self):
        return self.title


class Recipe(models.Model):
    # relations
    category = models.ForeignKey(Category, verbose_name='Kateqoriya', on_delete=models.CASCADE, db_index=True, related_name='recipes')
    tags = models.ManyToManyField(Tag, verbose_name='Tags', related_name='recipes')
    author = models.ForeignKey(USER_MODEL, on_delete=models.CASCADE, db_index=True, related_name='recipes')

    # informations
    title = models.CharField('Basligi', max_length=120)
    short_description = models.CharField('Qisa Mezmunu', max_length=255, help_text='Bu sahe repestler siyahisinda reseptin mezmunu olaraq gorunur...')
    image = models.ImageField('Sekil', upload_to='recipes')
    long_description = RichTextField('Genis mezmunu')
    show_home_page = models.BooleanField(default=False)
    # author = models.CharField('Muellif', max_length=50)

    # moderations
    min_read_time = models.PositiveIntegerField('Min read time', editable=False, default=1)
    slug = models.SlugField('slug', max_length=255, editable=False, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_published = models.BooleanField('is published', default=True)

    class Meta: # table name: stroies_recipe
        # app_label = 'story'
        # db_table = 'resept'
        verbose_name = 'Resept'
        verbose_name_plural = 'Reseptler'
        ordering = ('-created_at', '-title')

    def __str__(self):
        return f"{self.title} category: {self.category}"

    def save(self, *args, **kwargs):
        article_word_count = len(self.long_description.split(' '))
        self.min_read_time = math.ceil(article_word_count/120)
        if not self.slug:
            self.slug = f"{slugify(self.title)}-{datetime.now().strftime('%Y%m%d-%H%M%S')}"
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse_lazy('recipe_detail', kwargs={'slug': self.slug }) #f'/stories/{self.slug}/'


class Story(models.Model):
    # relations
    category = models.ForeignKey(Category, verbose_name='Kateqoriya', on_delete=models.CASCADE, db_index=True, related_name='stories')
    tags = models.ManyToManyField(Tag, verbose_name='Tags', related_name='stories')
    author = models.ForeignKey(USER_MODEL, on_delete=models.CASCADE, db_index=True, related_name='stories')

    # informations
    title = models.CharField('Basligi', max_length=120)
    image = models.ImageField('Sekil', upload_to='recipes')
    long_description = RichTextField('Genis mezmunu')
    # author = models.CharField('Muellif', max_length=50)

    # moderations
    slug = models.SlugField('slug', max_length=255, editable=False, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    min_read_time = models.PositiveIntegerField('Min read time', editable=False, default=1)
    is_published = models.BooleanField('is published', default=True)

    class Meta: # table name: stroies_recipe
        # app_label = 'story'
        # db_table = 'resept'
        verbose_name = 'Hekaye'
        verbose_name_plural = 'Hekayeler'
        ordering = ('-created_at', '-title')

    def __str__(self):
        return f"{self.title} category: {self.category}"

    def save(self, *args, **kwargs):
        article_word_count = len(self.long_description.split(' '))
        self.min_read_time = math.ceil(article_word_count/120)
        if not self.slug:
            self.slug = f"{slugify(self.title)}-{datetime.now().strftime('%Y%m%d-%H%M%S')}"
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse_lazy('story_detail', kwargs={'slug': self.slug }) #f'/stories/{self.slug}/'


class Comment(models.Model):
    # relations
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE, related_name='comments')
    # story to do add story model and relation here
    user = models.ForeignKey(USER_MODEL, related_name='comments', on_delete=models.CASCADE, null=True, blank=True)
    parent_comment = models.ForeignKey('self', related_name='child_comments', on_delete=models.CASCADE, null=True, blank=True)

    user_name = models.CharField('Name', max_length=50, null=True, blank=True)
    email = models.EmailField('Email', max_length=40, null=True, blank=True)
    # website = models.URLField('Website', null=True, blank=True)
    message = models.TextField('Message')


class Contact(models.Model):
    name = models.CharField('Name', max_length=40)
    email = models.EmailField('Email', max_length=40)
    subject = models.CharField('Subject', max_length=255)
    message = models.TextField('Message')

    # moderations
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta: 
        verbose_name = 'Contact'
        verbose_name_plural = 'Contacts'

    def __str__(self):
        return f"{self.name} subject: {self.subject}"

    def get_email(self):
        return self.email


class SavedArticle(models.Model):
    user = models.ForeignKey(USER_MODEL, on_delete=models.CASCADE, related_name='saved_articles',)
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE, related_name='recipe_saved_articles', null=True, blank=True)
    story = models.ForeignKey(Story, on_delete=models.CASCADE, related_name='story_saved_articles', null=True, blank=True)

    # moderations
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta: 
        verbose_name = 'Saved Article'
        verbose_name_plural = 'Saved Articles'

    def __str__(self):
        return f"{self.user} recipe: {self.recipe} story: {self.story}"


class Subscriber(models.Model):
    # information's
    email = models.EmailField('Email', max_length=30, unique=True)
    is_active = models.BooleanField('is active', default=True)

    # moderation's
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta: 
        verbose_name = 'Subscriber'
        verbose_name_plural = 'Subscribers'

    def __str__(self):
        return self.email


"""
|id | message | parent_id |
| 1 | Eladi | null |
| 2 | Chsdnfklsdf | 1 |
| 3 | Chsdnfklsdf | 1 |
| 4 | Chsdnfklsdf | null |
| 5 | Chsdnfklsdf | 2 |
"""

# 1,       4 
# 2, 3     []
# 5, []

food_stories/stories/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, \
    TemplateView, View
from django.urls import reverse_lazy

from stories.models import Category, Recipe, Story, SavedArticle
from stories.forms import ContactForm, StoryForm, RecipeForm, SubscriberForm
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseForbidden, HttpResponse
from django.core.exceptions import PermissionDenied

from stories.tasks import export_excel

# def home(request):
#     categories = Category.objects.all()[:3]
#     recipes = Recipe.objects.all()[:2]
#     context = {
#         'categories': categories,
#         'recipes': recipes
#     }
#     return render(request, 'index.html', context)


class HomePage(TemplateView):
    template_name = 'index.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data( *args, **kwargs)
        context['recipes'] = Recipe.objects.all().order_by('-show_home_page')[:2]
        context['categories'] = Category.objects.all()[:3]
        return context


def about(request):
    return render(request, 'about.html', )


def manage(request):
    return render(request, 'manage.html')

# def contact(request):
#     if request.method == 'POST':
#         form = ContactForm(request.POST)
#         if form.is_valid():
#             form.save()
#             messages.success(request, 'Mesajiniz gonderildi!!')
#             return redirect('/')
#         else:
#             messages.error(request, 'Mesajiniz gonderilmedi')
#     else:
#         form = ContactForm()
#     context = {
#         'form' : form
#     }
#     return render(request, 'contact.html', context)


class ContactView(CreateView):
    form_class = ContactForm
    template_name = 'contact.html'
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        messages.success(self.request, 'Mesajiniz gonderildi!!')
        return super().form_valid(form)


class CreateStoryView(LoginRequiredMixin, CreateView):
    form_class = StoryForm
    template_name = 'create_story.html'

    def form_valid(self, form):
        story = form.save(commit=False)
        story.author = self.request.user
        story.save()
        return super().form_valid(form)

from django.contrib.auth.mixins import PermissionRequiredMixin

class CreateRecipeView(LoginRequiredMixin, CreateView):
    form_class = RecipeForm
    template_name = 'create_recipe.html'
    # permission_required = ('stories.add_recipe',)

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_author:
            raise PermissionDenied
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        recipe = form.save(commit=False)
        recipe.author = self.request.user
        recipe.save()
        return super().form_valid(form)


def recipes(request):
    recipes = Recipe.objects.filter(is_published=True)
    context = {
        'recipes': recipes
    }
    return render(request, 'recipes.html', context)


class StoryListView(ListView):
    model = Story
    template_name = 'stories.html'
    paginate_by = 3

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(is_published=True)


class StoryDetailView(DetailView):
    model = Story # context object ve story adlari ile template fetch
    template_name = 'single.html'
    # context_object_name = 'story_detail'


class StoryUpdateView(UpdateView):
    form_class = StoryForm
    model = Story
    template_name = 'create_story.html'


class StoryDeleteView(DeleteView):
    model = Story
    success_url = reverse_lazy('stories')
    http_method_names = ('get',)

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)


def recipe_detail(request, slug):
    print(slug)
    # recipe = Recipe.objects.get(slug=slug)
    recipe = get_object_or_404(Recipe, slug=slug)
    context = {
        'object': recipe
    }
    return render(request, 'single.html', context)

class SaveRecipeView(View):
    def get(self, *args, **kwargs):
        recipe_id = kwargs.get('pk')
        message = 'Melumat elave edildi'
        recipe = get_object_or_404(Recipe, id=recipe_id)
        
        if self.request.user.is_authenticated:
            save_article, created = SavedArticle.objects.get_or_create(user=self.request.user, recipe=recipe)
            if not created:
                message = 'Melumat evvel elave edilmisdi'
            response = HttpResponse(message)
        else:
            saved_articles = self.request.COOKIES.get('saved_articles', '')
            print('saved_articles', saved_articles)
            if str(recipe_id) not in saved_articles.split(';'):
                saved_articles += str(recipe_id) + ";"
            response = HttpResponse(message)
            response.set_cookie('saved_articles', saved_articles)
        # messages.success(self.request, message)
        return response


class SavedRecipeListView(ListView):
    model = Recipe
    template_name = 'saved_recipes.html'
    context_object_name = 'recipes'

    def get_queryset(self, ):
        if self.request.user.is_authenticated:
            queryset = super().get_queryset()
            user_saved_articles_ids = self.request.user.saved_articles.values_list('id', flat=True)
            return queryset.filter(id__in=user_saved_articles_ids)
        else:
            saved_recipes = self.request.COOKIES.get('saved_articles')
            if saved_recipes:
                saved_recipe_ids = [int(id) for id in saved_recipes.split(';') if id and id != 0]
                queryset = super().get_queryset()
                return queryset.filter(id__in=saved_recipe_ids)
            return None


def export_excel_view(request):
    export_excel.delay()
    return HttpResponse('Export edilir')


class SubscriberCreateView(CreateView):
    form_class = SubscriberForm
    # template_name = None
    http_method_names = ('post',)
    success_url = reverse_lazy('home')

    def get_success_url(self):
        redirect_url = self.request.GET.get('redirect_url', self.success_url)
        return redirect_url

    def form_valid(self, form):
        messages.success(self.request, 'Subscribe oldunuz')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.success(self.request, form.errors)
        redirect_url = self.request.GET.get('redirect_url', self.success_url)
        return redirect(redirect_url)

food_stories/stories/templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block title %} About {% endblock %}

{% block content %}

<section class="hero-wrap hero-wrap-2" style="background-image: url({% static 'images/bg_4.jpg' %});">
    <div class="overlay"></div>
    <div class="container">
        <div class="row no-gutters slider-text align-items-end justify-content-center">
            <div class="col-md-9 ftco-animate pb-5 text-center">
                <h1 class="mb-3 bread">About Us</h1>
                <p class="breadcrumbs"><span class="mr-2"><a href="index.html">Home <i
                        class="ion-ios-arrow-forward"></i></a></span> <span>About us<i
                        class="ion-ios-arrow-forward"></i></span></p>
            </div>
        </div>
    </div>
</section>

<section class="ftco-counter ftco-section ftco-no-pt ftco-no-pb img" id="section-counter">
    <div class="container">
        <div class="row d-flex">
            <div class="col-md-6 d-flex">
                <div class="img d-flex align-self-stretch" style="background-image:url({% static 'images/about.jpg' %});"></div>
            </div>
            <div class="col-md-6 pl-md-5 py-5">
                <div class="row justify-content-start pb-3">
                    <div class="col-md-12 heading-section ftco-animate">
                        <h2 class="mb-4"><span>About Stories</span></h2>
                        <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia</p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6 justify-content-center counter-wrap ftco-animate">
                        <div class="block-18 text-center py-5 bg-light mb-4">
                            <div class="text">
                                <strong class="number" data-number="100">0</strong>
                                <span>Daily visitors</span>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6 justify-content-center counter-wrap ftco-animate">
                        <div class="block-18 text-center py-5 bg-light mb-4">
                            <div class="text">
                                <strong class="number" data-number="200">0</strong>
                                <span>Stories</span>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6 justify-content-center counter-wrap ftco-animate">
                        <div class="block-18 text-center py-5 bg-light mb-4">
                            <div class="text">
                                <strong class="number" data-number="300">0</strong>
                                <span>Recipes</span>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6 justify-content-center counter-wrap ftco-animate">
                        <div class="block-18 text-center py-5 bg-light mb-4">
                            <div class="text">
                                <strong class="number" data-number="40">0</strong>
                                <span>Users</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>


{% endblock %}

food_stories/stories/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <title>{% block title %} Home {% endblock %} | Stories</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Poppins:200,300,400,500,600,700,900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:400,400i,700,700i,900,900i" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'css/open-iconic-bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">

    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">

    <link rel="stylesheet" href="{% static 'css/aos.css' %}">

    <link rel="stylesheet" href="{% static 'css/ionicons.min.css' %}">

    <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'css/icomoon.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link rel="stylesheet" href="http:////netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
    <style>
        li.success{
            background-color: green;
            width: 100%;
            color: white;
        }
        li.error{
            background-color: red;
            width: 100%;
            color: white;
        }
    </style>
    {% block css %}
    {% endblock %}
</head>

<body>
    {% include 'includes/navbar.html' %}

    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
    
        {% block content %}

        {% endblock %}


    {% include 'includes/subscribers.html' %}

    {% include 'includes/footer.html' %}

    <!-- loader -->
    <div id="ftco-loader" class="show fullscreen">
        <svg class="circular" width="48px" height="48px">
        <circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/>
        <circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10"
                stroke="#F96D00"/>
    </svg>
    </div>
    <div id="snackbar">Some text some message..</div>

    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/jquery-migrate-3.0.1.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
    <script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
    <script src="{% static 'js/jquery.stellar.min.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'js/aos.js' %}"></script>
    <script src="{% static 'js/jquery.animateNumber.min.js' %}"></script>
    <script src="{% static 'js/scrollax.min.js' %}"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
    <script src="{% static 'js/google-map.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>


    <script>

        document.querySelector('.subscribe-form').addEventListener('submit', (e)=>{
            e.preventDefault();
            var form_data = {
                'email': document.querySelector('[name="email"]').value,
            };

            $.ajax({
                url:"{% url 'subscribe' %}",
                method: "POST",
                data: form_data,
                success: function(response, textStatus, xhr){
                    console.log(response);
                    if (xhr.status == 201){
                        show_message('Ugurla subscribe oldunuz!');
                    }
                },
                error: function(error_resp){
                    console.log(error_resp);
                    response = error_resp.responseJSON;
                    for(let error_key in response){
                        show_message(response[error_key]);
                    }
                }
            })

       
        });

        function show_message(message) {
            var x = document.getElementById("snackbar");
            x.innerText = message;
            x.className = "show";
            setTimeout(function(){ x.className = x.className.replace("show", ""); }, 3000);
        }

    </script>

    {% block js %}
    {% endblock %}

</body>

</html>

food_stories/stories/templates/stories.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Stories {% endblock %}

{% block content %}


<section class="hero-wrap hero-wrap-2" style="background-image: url('{% static 'images/bg_4.jpg' %}');">
    <div class="overlay"></div>
    <div class="container">
        <div class="row no-gutters slider-text align-items-end justify-content-center">
            <div class="col-md-9 ftco-animate pb-5 text-center">
                <h1 class="mb-3 bread">Stories</h1>
                <p class="breadcrumbs"><span class="mr-2"><a href="index.html">Home <i
                        class="ion-ios-arrow-forward"></i></a></span> <span>Stories <i
                        class="ion-ios-arrow-forward"></i></span>
                </p>
            </div>
        </div>
    </div>
</section>


<section class="ftco-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-9">
                <div class="row">
                    {% for story in story_list %}
                    <div class="col-md-4 ftco-animate">
                        <div class="blog-entry">
                            <a href="{{ story.get_absolute_url }}" class="img-2"><img src="{{ story.image.url }}" class="img-fluid"
                                                                     alt="Colorlib Template"></a>
                            <div class="text pt-3">
                                <p class="meta d-flex"><span class="pr-3">{{ story.category.title }}</span><span class="ml-auto pl-3">{{story.created_at|date:"F d, Y"}}</span>
                                </p>
                                <h3><a href="{{ story.get_absolute_url }}">{{story.title}}</a></h3>
                                <p class="mb-0"><a href="{{ story.get_absolute_url }}" class="btn btn-black py-2">Read More <span
                                        class="icon-arrow_forward ml-4"></span></a></p>
                            </div>
                        </div>
                    </div>
                    {% empty %}
                    <h3>Göstəriləcək məlumat yoxdur</h3>
                    {% endfor %}

                </div>
                <div class="row mt-5">
                    <div class="col text-center">
                        <div class="block-27">
                            <ul>
                                {% if page_obj.has_previous %}
                                    <li><a href="?page={{ page_obj.previous_page_number }}">&lt;</a></li>
                                {% endif %}
                                
                                {% for page in page_obj.paginator.page_range %}
                                    {% if page == page_obj.number %}
                                        <li class="active"><span>{{page}}</span></li>
                                    {% else %}
                                        <li><a href="?page={{page}}">{{page}}</a></li>
                                    {% endif %}
                                {% endfor %}
                                
                                {% if page_obj.has_next %}
                                    <li><a href="?page={{ page_obj.paginator.num_pages }}">&gt;</a></li>
                                {% endif %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-lg-3">
                <div class="sidebar-wrap">
                    <div class="sidebar-box p-4 about text-center ftco-animate">
                        <h2 class="heading mb-4">About Me</h2>
                        <img src="images/author.jpg" class="img-fluid" alt="Colorlib Template">
                        <div class="text pt-4">
                            <p>Hi! My name is <strong>Cathy Deon</strong>, behind the word mountains, far from the
                                countries Vokalia and Consonantia, there live the blind texts. Separated they live in
                                Bookmarksgrove right at the coast of the Semantics, a large language ocean.</p>
                        </div>
                    </div>
                    <div class="sidebar-box p-4 ftco-animate">
                        <form action="#" class="search-form">
                            <div class="form-group">
                                <span class="icon icon-search"></span>
                                <input type="text" class="form-control" placeholder="Search">
                            </div>
                        </form>
                    </div>
                    <div class="sidebar-box categories text-center ftco-animate">
                        <h2 class="heading mb-4">Categories</h2>
                        <ul class="category-image">
                            <li>
                                <a href="#" class="img d-flex align-items-center justify-content-center text-center"
                                   style="background-image: url(images/category-1.jpg);">
                                    <div class="text">
                                        <h3>Foods</h3>
                                    </div>
                                </a>
                            </li>
                            <li>
                                <a href="#" class="img d-flex align-items-center justify-content-center text-center"
                                   style="background-image: url(images/category-2.jpg);">
                                    <div class="text">
                                        <h3>Lifestyle</h3>
                                    </div>
                                </a>
                            </li>
                            <li>
                                <a href="#" class="img d-flex align-items-center justify-content-center text-center"
                                   style="background-image: url(images/category-2.jpg);">
                                    <div class="text">
                                        <h3>Others</h3>
                                    </div>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>


{% endblock %}