food_stories/accounts/urls.py
from django.urls import path, re_path
from accounts.views import register, UserProfile, CustomLoginView, activate, CustomPasswordChangeView, \
    ForgetPasswordView, CustomPasswordResetConfirmView
from django.contrib.auth.views import LogoutView


urlpatterns = [

    path('register/', register, name='register'),
    path('login/', CustomLoginView.as_view(), name='login'),
    re_path(r'activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/', activate, name='activation'),
    re_path(r'password-reset-confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/', CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('change-password/', CustomPasswordChangeView.as_view(), name='change_password'),
    path('forget-password/', ForgetPasswordView.as_view(), name='forget_password'),
    path('user-profile/', UserProfile.as_view(), name='user_profile'),

]

food_stories/api/urls.py
from django.urls import path
from api.views import recipes_api, recipe, SubscriberCreateAPIView
from api.routers import router

urlpatterns = [
    path('recipes/', recipes_api, name='api_recipes'),
    path('recipes/<int:id>/', recipe, name='api_recipe'),
    path('subscribe/', SubscriberCreateAPIView.as_view(), name='subscribe'),
] + router.urls

food_stories/food_stories/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('jet/', include('jet.urls', 'jet')),  # Django JET URLS
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS
    path('admin/', admin.site.urls),
    path('', include('stories.urls')),
    path('api/v1.0/', include('api.urls')),
    path('api/v1.0/auth/', include('accounts.api.urls', namespace='api_account')),
    path('', include('social_django.urls', namespace="social")),
    path('auth/', include('accounts.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
] 

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

food_stories/stories/urls.py
from django.urls import path
from stories.views import HomePage, about, recipes, recipe_detail, StoryListView, StoryDetailView, ContactView, \
    CreateStoryView, StoryUpdateView, StoryDeleteView, manage, CreateRecipeView, SaveRecipeView, \
        SavedRecipeListView, export_excel_view, SubscriberCreateView

urlpatterns = [
    path('', HomePage.as_view(), name='home'),
    path('about/', about, name='about'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('recipes/', recipes, name='recipes'),
    path('stories/', StoryListView.as_view(), name='stories'),
    path('create-story/', CreateStoryView.as_view(), name='create_story'),
    path('create-recipe/', CreateRecipeView.as_view(), name='create_recipe'),
    path('delete-story/<str:slug>/', StoryDeleteView.as_view(), name='delete_story'),
    path('update-story/<str:slug>/', StoryUpdateView.as_view(), name='update_story'),
    path('stories/<str:slug>/', StoryDetailView.as_view(), name='story_detail'),
    path('recipes/<str:slug>/', recipe_detail, name='recipe_detail'),
    path('save-recipe/<int:pk>/', SaveRecipeView.as_view(), name='save_recipe'),
    path('saved-recipes/', SavedRecipeListView.as_view(), name='saved_recipes'),
    path('manage/', manage, name='manage'),
    path('export/', export_excel_view, name='export_excel_view'),
    path('subscribe/', SubscriberCreateView.as_view(), name='subscribe'),
]

food_stories/stories/forms.py
from django import forms
from stories.models import Contact, Recipe, Story, Category, Tag, Subscriber
# from ckeditor.widgets import CKEditorWidget
from ckeditor_uploader.widgets import CKEditorUploadingWidget

class ContactForm(forms.ModelForm):
    phone_number = forms.CharField(max_length=13, initial='+994', min_length=7, widget=forms.TextInput(attrs={
                    'class': 'form-control',
                    'placeholder': 'Phone Number',
                }), help_text='Sizinle elaqeye kecmeyimiz ucun nomre daxil etmeyiniz sertdir!')
    class Meta:
        model = Contact
        fields = (
            'name',
            'email',
            'subject',
            'phone_number',
            'message',
           
        )
        widgets = {
            'name': forms.TextInput(attrs={
                    'class': 'form-control',
                    'placeholder': 'Your name',
                }),
            'email': forms.EmailInput(attrs={
                    'class': 'form-control',
                    'placeholder': 'Your email',
                }),
            'subject': forms.TextInput(attrs={
                    'class': 'form-control',
                    'placeholder': 'Subject',
                }),
            'message': forms.Textarea(attrs={
                    'class': 'form-control',
                    'placeholder': 'Message',
                    'rows': 7,
                    'cols': 30,
                })
        }

    
    def clean(self):
        print('here')
        cleaned_data = super().clean()
        print(cleaned_data)

    # def clean_phone_number(self):
    #     phone_number = self.changed_data.get('phone_number')



class RecipeAdminForm(forms.ModelForm):
    long_description = forms.CharField(widget=CKEditorUploadingWidget())
    class Meta:
        model = Recipe
        fields = '__all__'


class StoryForm(forms.ModelForm):
    category = forms.ModelChoiceField(queryset=Category.objects.all(), widget=forms.Select(attrs={
                    'class': 'form-control'
                }))
    tags =  forms.ModelMultipleChoiceField(queryset=Tag.objects.all(), widget=forms.SelectMultiple(attrs={
                    'class': 'form-control',
                }) )
    class Meta:
        model = Story
        fields = ('title', 'category', 'tags', 'long_description', 'image',)
        widgets = {
            'title': forms.TextInput(attrs={
                    'class': 'form-control',
                    'placeholder': 'Title',
                }),
            'long_description': CKEditorUploadingWidget(),

        }


class RecipeForm(forms.ModelForm):
    category = forms.ModelChoiceField(queryset=Category.objects.all(), widget=forms.Select(attrs={
                    'class': 'form-control'
                }))
    tags =  forms.ModelMultipleChoiceField(queryset=Tag.objects.all(), widget=forms.SelectMultiple(attrs={
                    'class': 'form-control',
                }) )
    class Meta:
        model = Recipe
        fields = ('title', 'category', 'tags', 'short_description', 'long_description', 'image',)
        widgets = {
            'title': forms.TextInput(attrs={
                    'class': 'form-control',
                    'placeholder': 'Title',
                }),
            'long_description': CKEditorUploadingWidget(),

        }


class SubscriberForm(forms.ModelForm):

    class Meta:
        model = Subscriber
        fields = (
            'email',
        )

        widgets = {
            'email': forms.EmailInput(attrs={
                'class':  'form-control',
                'placeholder': 'Enter email address',
            })
        }










    # name = forms.CharField(label='Name', widget=forms.TextInput(attrs={
    #     'class': 'form-control',
    #     'placeholder': 'Your name',
    # }), max_length=40)
    # email = forms.EmailField(label='Email', widget=forms.EmailInput(attrs={
    #     'class': 'form-control',
    #     'placeholder': 'Your email',
    # }), max_length=40)
    # subject = forms.CharField(label='Subject', widget=forms.TextInput(attrs={
    #     'class': 'form-control',
    #     'placeholder': 'Subject',
    # }), max_length=255)
    # message = forms.CharField(label='Message', required=False, widget=forms.Textarea(attrs={
    #     'class': 'form-control',
    #     'placeholder': 'Message',
    #     'rows': 7,
    #     'cols': 30,
    # }))

food_stories/stories/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, \
    TemplateView, View
from django.urls import reverse_lazy

from stories.models import Category, Recipe, Story, SavedArticle
from stories.forms import ContactForm, StoryForm, RecipeForm, SubscriberForm
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseForbidden, HttpResponse
from django.core.exceptions import PermissionDenied

from stories.tasks import export_excel

# def home(request):
#     categories = Category.objects.all()[:3]
#     recipes = Recipe.objects.all()[:2]
#     context = {
#         'categories': categories,
#         'recipes': recipes
#     }
#     return render(request, 'index.html', context)


class HomePage(TemplateView):
    template_name = 'index.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data( *args, **kwargs)
        context['recipes'] = Recipe.objects.all().order_by('-show_home_page')[:2]
        context['categories'] = Category.objects.all()[:3]
        return context


def about(request):
    return render(request, 'about.html', )


def manage(request):
    return render(request, 'manage.html')

# def contact(request):
#     if request.method == 'POST':
#         form = ContactForm(request.POST)
#         if form.is_valid():
#             form.save()
#             messages.success(request, 'Mesajiniz gonderildi!!')
#             return redirect('/')
#         else:
#             messages.error(request, 'Mesajiniz gonderilmedi')
#     else:
#         form = ContactForm()
#     context = {
#         'form' : form
#     }
#     return render(request, 'contact.html', context)


class ContactView(CreateView):
    form_class = ContactForm
    template_name = 'contact.html'
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        messages.success(self.request, 'Mesajiniz gonderildi!!')
        return super().form_valid(form)


class CreateStoryView(LoginRequiredMixin, CreateView):
    form_class = StoryForm
    template_name = 'create_story.html'

    def form_valid(self, form):
        story = form.save(commit=False)
        story.author = self.request.user
        story.save()
        return super().form_valid(form)

from django.contrib.auth.mixins import PermissionRequiredMixin

class CreateRecipeView(LoginRequiredMixin, CreateView):
    form_class = RecipeForm
    template_name = 'create_recipe.html'
    # permission_required = ('stories.add_recipe',)

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_author:
            raise PermissionDenied
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        recipe = form.save(commit=False)
        recipe.author = self.request.user
        recipe.save()
        return super().form_valid(form)


def recipes(request):
    recipes = Recipe.objects.filter(is_published=True)
    context = {
        'recipes': recipes
    }
    return render(request, 'recipes.html', context)


class StoryListView(ListView):
    model = Story
    template_name = 'stories.html'
    paginate_by = 3

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(is_published=True)


class StoryDetailView(DetailView):
    model = Story # context object ve story adlari ile template fetch
    template_name = 'single.html'
    # context_object_name = 'story_detail'


class StoryUpdateView(UpdateView):
    form_class = StoryForm
    model = Story
    template_name = 'create_story.html'


class StoryDeleteView(DeleteView):
    model = Story
    success_url = reverse_lazy('stories')
    http_method_names = ('get',)

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)


def recipe_detail(request, slug):
    print(slug)
    # recipe = Recipe.objects.get(slug=slug)
    recipe = get_object_or_404(Recipe, slug=slug)
    context = {
        'object': recipe
    }
    return render(request, 'single.html', context)

class SaveRecipeView(View):
    def get(self, *args, **kwargs):
        recipe_id = kwargs.get('pk')
        message = 'Melumat elave edildi'
        recipe = get_object_or_404(Recipe, id=recipe_id)
        
        if self.request.user.is_authenticated:
            save_article, created = SavedArticle.objects.get_or_create(user=self.request.user, recipe=recipe)
            if not created:
                message = 'Melumat evvel elave edilmisdi'
            response = HttpResponse(message)
        else:
            saved_articles = self.request.COOKIES.get('saved_articles', '')
            print('saved_articles', saved_articles)
            if str(recipe_id) not in saved_articles.split(';'):
                saved_articles += str(recipe_id) + ";"
            response = HttpResponse(message)
            response.set_cookie('saved_articles', saved_articles)
        # messages.success(self.request, message)
        return response


class SavedRecipeListView(ListView):
    model = Recipe
    template_name = 'saved_recipes.html'
    context_object_name = 'recipes'

    def get_queryset(self, ):
        if self.request.user.is_authenticated:
            queryset = super().get_queryset()
            user_saved_articles_ids = self.request.user.saved_articles.values_list('id', flat=True)
            return queryset.filter(id__in=user_saved_articles_ids)
        else:
            saved_recipes = self.request.COOKIES.get('saved_articles')
            if saved_recipes:
                saved_recipe_ids = [int(id) for id in saved_recipes.split(';') if id and id != 0]
                queryset = super().get_queryset()
                return queryset.filter(id__in=saved_recipe_ids)
            return None


def export_excel_view(request):
    export_excel.delay()
    return HttpResponse('Export edilir')


class SubscriberCreateView(CreateView):
    form_class = SubscriberForm
    # template_name = None
    http_method_names = ('post',)
    success_url = reverse_lazy('home')

    def get_success_url(self):
        redirect_url = self.request.GET.get('redirect_url', self.success_url)
        return redirect_url

    def form_valid(self, form):
        messages.success(self.request, 'Subscribe oldunuz')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.success(self.request, form.errors)
        redirect_url = self.request.GET.get('redirect_url', self.success_url)
        return redirect(redirect_url)

food_stories/stories/templates/includes/footer.html
<footer class="ftco-footer ftco-footer-2 ftco-section">
    <div class="container">
        <div class="row mb-5">
            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">Stories</h2>
                    <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
                    <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
                        <li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
                        <li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
                        <li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md">
                <div class="ftco-footer-widget mb-4 ml-md-5">
                    <h2 class="ftco-heading-2">Information</h2>
                    <ul class="list-unstyled">
                        <li><a href="#" class="py-2 d-block">Terms of Uses</a></li>
                        <li><a href="#" class="py-2 d-block">About Stories</a></li>
                        <li><a href="#" class="py-2 d-block">Privacy Policy</a></li>
                        <li><a href="#" class="py-2 d-block">Accessibility Help</a></li>
                        <li><a href="#" class="py-2 d-block">Advertise with us</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">Categories</h2>
                    <ul class="list-unstyled">
                        <li><a href="#" class="py-2 d-block">Food</a></li>
                        <li><a href="#" class="py-2 d-block">Restaurant</a></li>
                        <li><a href="#" class="py-2 d-block">Dessert</a></li>
                        <li><a href="#" class="py-2 d-block">Lifestyle</a></li>
                        <li><a href="#" class="py-2 d-block">Recipes</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">Have a Questions?</h2>
                    <div class="block-23 mb-3">
                        <ul>
                            <li><span class="icon icon-map-marker"></span><span class="text">203 Fake St. Mountain View, San Francisco, California, USA</span>
                            </li>
                            <li><a href="#"><span class="icon icon-phone"></span><span
                                class="text">+2 392 3929 210</span></a></li>
                            <li><a href="#"><span class="icon icon-envelope"></span><span class="text">info@yourdomain.com</span></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 text-center">

                <p>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    Copyright &copy;
                    <script>
                        document.write(new Date().getFullYear());
                    </script>
                    All rights reserved | This template is made with <i class="icon-heart color-danger" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                </p>
            </div>
        </div>
    </div>
</footer>

food_stories/stories/templates/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark ftco-navbar-light" id="ftco-navbar">
    <div class="container">
        <a class="navbar-brand" href="index.html">Stories<span>.</span></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="oi oi-menu"></span> Menu
    </button>

        <div class="collapse navbar-collapse" id="ftco-nav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active"><a href="{% url 'home' %}" class="nav-link">Home</a></li>
                <li class="nav-item"><a href="{% url 'about' %}" class="nav-link">About</a></li>
                <li class="nav-item"><a href="{% url 'stories' %}" class="nav-link">Stories</a></li>

                <li class="nav-item"><a href="{% url 'recipes' %}" class="nav-link">Recipes</a></li>
                <li class="nav-item"><a href="{% url 'contact' %}" class="nav-link">Contact</a></li>
                <li class="nav-item"><a href="{% url 'api_account:register' %}" class="nav-link">Auth APi</a></li>
                <li class="nav-item"><a href="{% url 'saved_recipes' %}" class="nav-link">Saved Articles</a></li>
                {% if request.user.is_authenticated %}
                    <li><a href="{% url 'logout' %}" class="btn btn-black px-3 px-md-4 py-3">Log Out</a></li>
                {% else %} 
                    <li><a href="{% url 'login' %}" class="btn btn-black px-3 px-md-4 py-3">Sign in</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
<!-- END nav -->

food_stories/stories/templates/includes/subscribers.html
{% load custom_tags %}

{% get_subscriber_form as form %}
<section class="ftco-subscribe ftco-section bg-light">
    <div class="overlay">
        <div class="container">
            <div class="row d-flex justify-content-center">
                <div class="col-md-8 text-wrap text-center heading-section ftco-animate">
                    <h2 class="mb-4"><span>Subcribe to our Newsletter</span></h2>
                    <p>A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth.</p>
                    <div class="row d-flex justify-content-center mt-4 mb-4">
                        <div class="col-md-8">
                            <form method="POST" class="subscribe-form">
                                <div class="form-group d-flex">
                                    {{form.email}}
                                    {{form.email.help_text}}
                                    <!-- <input type="text" class="form-control" placeholder="Enter email address"> -->
                                    <input type="submit" value="Subscribe" class="submit px-3">
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>